# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
    - 3.7
    - 3.8

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update -q conda
    - conda install -c conda-forge conda-build anaconda-client pytest pytest-cov nbval
    - conda config --set auto_update_conda no
    - conda info -a
    - pip install .

script:
    - pytest -v --color=yes --cov=venim --nbval tests
after_success:
    - conda install -c conda-forge codecov
    - codecov
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
# deploy:
#     provider: pypi
#     distributions: sdist bdist_wheel
#     user: michaelaye
#     password:
#         secure: PLEASE_REPLACE_ME
#     on:
#         tags: true
#         repo: michaelaye/venim
